### ISSUE TITLE
How to build openvpn_windows?

### ISSUE THREAD

**Issue by qazhub** [mullvad/mullvadvpn-app-binaries#97]
It's not clear how to build openvpn_windows target. According to the README:

> Building openvpn.exe for Windows is done by cross-compiling from Linux using a mingw-w64 toolchain. You need to do this build on a recent Debian or Ubuntu release, one should generally follow the instructions laid out in the OpenVPN's build system docs. Currently, this has only been tested with Debian 9.
> 
> ...
> 
> `./setup-generic-buildsystem.6.sh`

This seems to imply one can get `openvpn.exe` file by running `make openvpn_windows` on a Debian 9 Linux machine, is that right?

Upon trying this on a Debian 9 machine, I can't get it to even pass the autoreconf phase, see the logs:

<details>
<pre><code>
...... [lz4 succcessfully built, so output omitted] ......
# lz4 always installs a shared library. Unless it's removed                                                                                                  
# OpenVPN will link against it.                                                 
rm /root/mullvadvpn-app-binaries/build/lib/liblz4.*so*                                                            
rm -rf "openvpn-build/generic/tmp"                                              
mkdir -p openvpn-build/generic/tmp                                                                                 
mkdir -p openvpn-build/generic/sources                                           
ln -sf /root/mullvadvpn-app-binaries/lz4 openvpn-build/generic/tmp/lz4                                            
ln -sf /root/mullvadvpn-app-binaries/openssl openvpn-build/generic/tmp/openssl-1.1.1j
ln -sf /root/mullvadvpn-app-binaries/openvpn openvpn-build/generic/tmp/openvpn-2.5.3                                     
cd openvpn; autoreconf -f -v                                                     
autoreconf: Entering directory `.'                                                                                       
autoreconf: configure.ac: not using Gettext                                      
autoreconf: running: aclocal --force -I m4                                                                               
autoreconf: configure.ac: tracing                                                
autoreconf: configure.ac: not running libtoolize: --install not given                                               
autoreconf: running: /usr/bin/autoconf --force                                   
autoreconf: running: /usr/bin/autoheader --force                                                                        
autoreconf: running: automake --force-missing                                    
configure.ac:392: error: required file './ltmain.sh' not found                                                            
src/openvpnmsica/Makefile.am:48: warning: source file '$(top_srcdir)/src/tapctl/error.c' is in a subdirectory,                                                           
src/openvpnmsica/Makefile.am:48: but option 'subdir-objects' is disabled                                         
automake: warning: possible forward-incompatibility.                                                                                                                     
automake: At least a source file is in a subdirectory, but the 'subdir-objects'                                   
automake: automake option hasn't been enabled.  For now, the corresponding output                                                                                        
automake: object file(s) will be placed in the top-level directory.  However,                                           
automake: this behaviour will change in future Automake versions: they will                                                                                              
automake: unconditionally cause object files to be placed in the same subdirectory                                      
automake: of the corresponding sources.                                                                                                                                  
automake: You are advised to start using 'subdir-objects' option throughout your                                              
automake: project, to avoid future incompatibilities.                           
src/openvpnmsica/Makefile.am:48: warning: source file '$(top_srcdir)/src/tapctl/tap.c' is in a subdirectory,            
src/openvpnmsica/Makefile.am:48: but option 'subdir-objects' is disabled                 
src/openvpnserv/Makefile.am:32: warning: source file '$(top_srcdir)/src/openvpn/block_dns.c' is in a subdirectory,
src/openvpnserv/Makefile.am:32: but option 'subdir-objects' is disabled
...... [some more warnings just like the above, so omitted] ......
tests/unit_tests/openvpn/Makefile.am:68: warning: source file '$(openvpn_srcdir)/platform.c' is in a subdirectory,
tests/unit_tests/openvpn/Makefile.am:68: but option 'subdir-objects' is disabled
tests/unit_tests/openvpn/Makefile.am:68: warning: source file '$(openvpn_srcdir)/run_command.c' is in a subdirectory,
tests/unit_tests/openvpn/Makefile.am:68: but option 'subdir-objects' is disabled
tests/unit_tests/plugins/auth-pam/Makefile.am:10: warning: source file '$(sut_sourcedir)/utils.c' is in a subdirectory,
tests/unit_tests/plugins/auth-pam/Makefile.am:10: but option 'subdir-objects' is disabled
autoreconf: automake failed with exit status: 1
Makefile:136: recipe for target 'openvpn_windows' failed
make: *** [openvpn_windows] Error 1
</code></pre>
</details>

**Comment by dlon** [comment]
Try running `cd openvpn; autoreconf -i` before building it again. It should copy the missing file to that directory.

Thanks for pointing this out. The makefile should probably include this flag. :)

**Comment by qazhub** [comment]
Yeah I figured it out after some time. By running `cd openvpn; libtoolize` I was able to work around this issue. Just wondered how you were building it.
